apiVersion: kaptain.org/1.19
kind: basic-quality-and-versioning
metadata:
  description: "GCP GKE cluster management build flow as a postVersionsAndNaming hook"
spec:
  main:
    hooks:
      postVersionsAndNaming: kaptain-out/gcp-gke-cluster-management-orchestrator.bash
    docker:
      platform: linux/amd64,linux/arm64
layer-payload:
  - source: /gcp-gke-cluster-management-orchestrator.bash
    destination: kaptain-out
  - source: /gcp-gke-cluster-management-defaults.bash
    destination: kaptain-out
  - source: /gcp-gke-cluster-management-prepare.bash
    destination: kaptain-out
  - source: /gcp-gke-cluster-management-pre-build-validate.bash
    destination: kaptain-out
  - source: /gcp-gke-cluster-management-post-build-validate.bash
    destination: kaptain-out
